# homebrew/bundle, homebrew/core, homebrew/services は現在のHomebrewでは
# 非推奨または不要（tapしようとするとエラーになり brew bundle 全体が失敗する）
# bufbuild/buf は untrusted tap 扱いでエラーになる上、bufはaqua.yamlで管理しているため削除
# nikitabobko/tap は参照するパッケージが無いため削除
brew "aqua"
brew "autoconf"
brew "openssl@3"
brew "gettext"
brew "bat"
brew "chezmoi"
brew "colordiff"
brew "direnv"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-secrets"
# aqua.yaml の gopls / goimports / dlv は go install でビルドされるため Go 本体が必要
brew "go"
# golangci-lint / grpcurl / buf は aqua.yaml でバージョン固定して管理しているため
# Brewfile からは外す（二重管理でバージョンが食い違うのを防ぐ）
brew "graphviz"
brew "htop"
# hubflow は homebrew/core から削除済みのため除外
brew "jq"
brew "lazygit"
brew "node-build"
brew "nodenv"
brew "peco"
brew "pipx"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python-yq"
brew "ripgrep"
brew "telnet"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "z"
cask "clipy"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "drawio"
cask "github"
cask "google-japanese-ime"
cask "imageoptim"
cask "keka"
cask "macdown"
cask "postman"
cask "proxyman"
cask "rancher"
cask "slack"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
